from . import appraisal_name_mixin
from . import appraisal
from . import appraisal_batch
from . import appraisal_batch_type
from . import appraisal_evaluation
from . import appraisal_evaluation_line
from . import appraisal_evaluation_template
from . import appraisal_evaluation_template_line
from . import appraisal_phase
from . import appraisal_question
from . import appraisal_question_group
from . import appraisal_question_selection
from . import appraisal_rate
from . import appraisal_rate_line
from . import appraisal_template
from . import appraisal_template_line
from . import hr_employee
from . import hr_job
from . import ir_model_fields
from . import appraisal_objective