# -*- coding: utf-8 -*-
{
    'name': 'Pragtech Tailoring Management',
    'version': '17.0',
    'category': 'Services',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'https://pragtech.co.in',
    'summary': 'Pragtech Tailoring Management',
    'description': 'Pragtech Tailoring Management',
    'depends': ['base', 'product', 'sale', 'hr', 'mail', 'contacts', 'website', 'website_sale', 'stock', 'purchase'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/assigning_tailor_wizard.xml',
        'wizard/assigning_measurement_wizard.xml',
        'views/template_delivery_email.xml',
        'views/delivered_product_email.xml',
        'views/template_shipped_mail.xml',
        'views/template_payment_email.xml',
        'views/view_fabrics.xml',
        'views/view_cloth_type.xml',
        'views/view_measurement.xml',
        'views/view_assigned_works.xml',
        'views/view_customer_measurement.xml',
        'views/view_feedback.xml',
        'views/inherit_stock_pickup.xml',
        'views/inherit_sale_order.xml',
        'views/inherit_product_page.xml',
        'views/inherit_product_category.xml',
        'views/inherit_employee.xml',
        'views/inherit_res_partner.xml',
        'views/customer_portal_inherit.xml',
        'views/customer_portal_invoice_inherit.xml',
        'webpage/webpage_home.xml',
        'webpage/webpage_feedback.xml',
        'webpage/measurement_popup.xml',
        'data/categories.xml',
        'views/menu.xml',
    ],
    'demo': ['demo/demo.xml'],
    'assets': {
        'web.assets_frontend': [
            'pragtech_tailoring_management/static/src/css/home.css',
            'pragtech_tailoring_management/static/src/css/shop.css',
            'pragtech_tailoring_management/static/src/js/measurement.js',
        ]
    },
    'images': ['static/description/pragtech_tailoring_management.gif'],
    'live_test_url': 'http://www.pragtech.co.in/company/proposal-form.html?id=103&name=Pragtech-Tailoring-Management',
    'currency': 'USD',
    'price': 499,
    'license': 'OPL-1',
    'installable': True,
    'application': False,
    'auto_install': False,
}
