{
    'name': 'WhatsApp Marketing',
    'version': '16.0.0.1.0.0',
    'author': "Digital Roots",
    'summary': """Provides a way to connect Odoo to your WhatsApp Business and use it for marketing""",
    'category': 'Marketing',
    'depends': ['base'],
    'license': 'OPL-1',
    "support": 'sales@digitalroots.com.kw',
    'website': 'https://digitalroots.com.kw',
    'price': 500.00,
    'currency': 'USD',
    'data': [
        'security/ir.model.access.csv',
        'views/res_config_settings_views.xml',
        'wizard/whatsapp_schedule_date_views.xml',
        'views/whatsapp_connector_views.xml',
        'data/ir_cron_data.xml',
    ],
    'external_dependencies': {'python': ['heyoo', 'PyYAML']},
    'demo': [],
    'installable': True,
    'application': True,
    "auto_install": False,
}
