# -*- coding: utf-8 -*-
{
'name': 'End of Service',
'version': '17.0.0.0.0',
'author': 'Openinside',
'license': 'OPL-1',
'price': 99.99,
'currency': 'USD',
'sequence': 10,
'category': 'Human Resources',
'website': 'https://www.open-inside.com',
'summary': 'End of Service, EOS, Employee End of Service, Benefits, EOS Contribution, '
           'Contribution, Reward, EOS Reward, Disengagement, Resignation',
'description': ''' Employee End of Service
''',
'depends': ['oi_payroll', 'oi_workflow'],
'data': ['security/res_groups.xml',
          'security/ir_rule.xml',
          'security/ir.model.access.csv',
          'view/hr_end_of_service_reason.xml',
          'view/hr_end_of_service_termination_reason.xml',
          'view/hr_end_of_service.xml',
          'view/hr_payslip.xml',
          'view/action.xml',
          'view/menu.xml',
          'data/approval_config.xml',
          'data/hr_end_of_service_reason.xml',
          'data/hr_end_of_service_termination_reason.xml',
          'data/hr_salary_rule.xml',
          'data/ir_config_parameter.xml',
          'data/ir_sequence.xml'],
'images': ['static/description/cover.png'],
'installable': True,
'odoo-apps': True,
'application': False
}